version: "3"
services:
  termci-api:
    build:
      dockerfile: docker/termci-api/Dockerfile
      context: ..
    container_name: termci-api
    restart: on-failure
    ports:
      - "9090:80"
    depends_on:
      termci-neo4j:
        condition: service_healthy
  termci-neo4j:
    image: neo4j:4.1.3
    container_name: termci-neo4j
    restart: always
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/data:/data
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/wrapper.sh:/opt/wrapper.sh
      - ./neo4j/initialize_neo4j.sh:/opt/initialize_neo4j.sh
      - ./neo4j/cyphers:/cyphers
    environment:
      - NEO4J_AUTH=$NEO4J_USERNAME/$NEO4J_PASSWORD
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 15s
      timeout: 10s
      retries: 10
    entrypoint: /opt/wrapper.sh

volumes:
  termci-neo4j:

